version: '3.9'
services:
  pgsrver:
    container_name: pgserver
    image: postgres
    #    networks:
    #      - network-1
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employee
  app:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: docker-project/app
    build: .
#      context: ./
#      dockerfile: local.Dockerfile
    container_name: spring-boot-docker

    #    networks:
    #      - network-1
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_SOURCE_URL=jdbc:postgresql://pgserver:5432/employee
      - SPRING_DATA_SOURCE_USERNAME=postgres
      - SPRING_DATA_SOURCE_PASSWORD=postgres
#    depends_on:
#      - pgserver
#networks:
#  network-1:







